version: '3.8'
services:
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000

  prod:
    build:
      context: .
      target: production
    ports:
      - 3000:3000
